# Site settings
title: ds31x's blog
url: "https://ds31x.github.io"
baseurl: ""
description: >
    이종립 선생님의 vimwiki로 구현한 기억보조 사이트.

# My information
email: dsaint31@gmail.com
author: ds31x
profile: A life lived solely by grace
twitter_username: dsaint31
github_username: ds31x
comment-support: utterances

# Build settings
plugins:
  - jekyll-paginate
  - jekyll-gist

permalink: /blog/:year/:month/:day/:title/

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

paginate: 10
paginator_path: "/blog"
paginate_path: "/blog/page:num/"

# Collections
collections:
    wiki:
        output: true
        permalink: /:collection/:path/

# Comment Service
giscus:
  repo: ds31x/ds31x.github.io
  repo_id: R_kgDOQ5Wjjw
  category: Announcements
  category_id: DIC_kwDOQ5Wjj84C07kQ

google_analytics:
  id: G-5XYKDG1M7F

google_adsense:
  client: ca-pub-3232161401562757

blame:   "https://github.com/ds31x/ds31x.github.io/blame/master/_wiki"
history: "https://github.com/ds31x/ds31x.github.io/commits/master/_wiki"
edit:    "https://github.com/ds31x/ds31x.github.io/edit/master/_wiki"
issue:   "https://github.com/ds31x/ds31x.github.io/issues/new"

timezone: "Asia/Seoul"

# https://kramdown.gettalong.org/rdoc/Kramdown/Options.html - smart_quotes
kramdown:
    smart_quotes: ["apos", "apos", "quot", "quot"]

search:
    page_size: 10     # 페이지당 결과수.
    debounce_ms: 200  # 검색 입력 debounce (ms)
